Sonarr New CFs
TRaSH-/Guides pull request #1008
Opened 2022-12-07 11:38 UTC by FonduemangVI

# Pull request

**Purpose**
New Bluray and Remux CFs for Sonarr

**Learning**
If you're adding a new Custom Format make sure you follow the [Radarr/Sonarr Custom Format (JSON) Guidelines](https://github.com/TRaSH-/Guides/blob/master/.github/CONTRIBUTING.md).

**Requirements**
Check all boxes as they are completed

- [ ] These changes meet the standards for [contributing](https://github.com/TRaSH-/Guides/blob/master/.github/CONTRIBUTING.md).
- [ ] I have read the [code of conduct](https://github.com/TRaSH-/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

2022-12-08 18:49 UTC, nuxencs reviewed
CF jsons look good to me, don't know enough about markdown to review those changes tho 😅

2022-12-08 22:07 UTC, TRaSH- requested changes
This shouldn't be added here, because then the remux tier will also be shown in the webdl guide section for Sonarr

2022-12-08 22:07 UTC, TRaSH- commented on includes/cf/sonarr-hq-source-group.md
> +    | [{{ sonarr['cf']['remux-tier-01']['name'] }}](/sonarr/sonarr-collection-of-custom-formats/#remux-tier-01)         | {{ sonarr['cf']['remux-tier-01']['trash_score'] }}     | {{ sonarr['cf']['rem
This shouldn't be added here, because then the remux tier will also be shown in the webdl guide section for Sonarr

2022-12-08 22:07 UTC, TRaSH- commented on includes/cf/sonarr-hq-source-group.md
> +    | [{{ sonarr['cf']['remux-tier-02']['name'] }}](/sonarr/sonarr-collection-of-custom-formats/#remux-tier-02)         | {{ sonarr['cf']['remux-tier-02']['trash_score'] }}     | {{ sonarr['cf']['rem
This shouldn't be added here, because then the remux tier will also be shown in the webdl guide section for Sonarr

2022-12-09 23:09 UTC, TRaSH- approved these changes

2022-12-09 23:12 UTC, merged