Add `Bravia Core` to Radarr Custom Formats Collection
TRaSH-/Guides pull request #1026
Opened 2022-12-16 22:39 UTC by quorn23

Added Bravia Core to Radarr collection

# Pull request

**Purpose**
Detailed description why you created this Pull Request.

**Approach**
If this Pull Request is created to solve a issue explain how does this change address the problem?

**Open Questions and Pre-Merge TODOs**
Check all boxes as they are completed

- [ ] Use github checklists. When solved, check the box and explain the answer.

**Learning**
If you're adding a new Custom Format make sure you follow the [Radarr/Sonarr Custom Format (JSON) Guidelines](https://github.com/TRaSH-/Guides/blob/master/.github/CONTRIBUTING.md).

**Requirements**
Check all boxes as they are completed

- [ ] These changes meet the standards for [contributing](https://github.com/TRaSH-/Guides/blob/master/.github/CONTRIBUTING.md).
- [ ] I have read the [code of conduct](https://github.com/TRaSH-/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

2022-12-17 03:43 UTC, TRaSH- requested changes
Now it only needs to show up in the guides,
Could you also add it to the includes.
https://github.com/TRaSH-/Guides/blob/master/includes/cf/radarr-streaming-services.md

2022-12-17 15:53 UTC, quorn23 commented
> Now it only needs to show up in the guides, Could you also add it to the includes. https://github.com/TRaSH-/Guides/blob/master/includes/cf/radarr-streaming-services.md

Added Bravia Core. Currently without a set score, might make sense to consider a score slightly higher than MA?

2022-12-17 16:28 UTC, owine commented
Should have the top streaming score IMO. Higher bitrate and better sound.

2023-01-06 21:24 UTC, TRaSH- approved these changes

2023-01-06 21:25 UTC, merged