feat(sonarr): added `Comedy Central` CF
TRaSH-/Guides pull request #1152
Opened 2023-02-14 18:47 UTC by nuxencs

# Pull request

**Purpose**
Comedy Central streaming service missing in Sonarr custom formats.

**Approach**
Added Comedy Central streaming service to the Sonarr custom formats.
Closes #1148 

**Requirements**
Check all boxes as they are completed

- [x] These changes meet the standards for [contributing](https://github.com/TRaSH-/Guides/blob/master/.github/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/TRaSH-/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

2023-02-15 08:39 UTC, TRaSH- requested changes
it still needs to be added also to the Sonarr v3 one
and then also to the collection page for v4 and the json for the v3 one for 3rd party sync tools.

Let me know if you are willing to do it, or that you want me to do it.

2023-02-15 11:49 UTC, nuxencs commented
Can do that once I get home, will be in a few hours

2023-02-15 18:52 UTC, nuxencs commented
should all be done, let me know if anything else needs to be done

2023-02-16 16:21 UTC, TRaSH- approved these changes

2023-02-16 16:23 UTC, merged