Convert Sonarr v3 quality definitions to MD table
TRaSH-/Guides pull request #137
Opened 2021-02-06 17:35 UTC by rcdailey

Eventually the screenshot should probably go away, but I've kept it in
for now to get a feel for the table. The table is important to allow for
the quality definition data to the parsed by a script.

2021-02-06 17:35 UTC, rcdailey commented
Please look very carefully at the min/max numbers in the table and verify I have accurately entered them according to the screenshot. Thank you.

2021-02-06 17:40 UTC, bakerboy448 requested changes

2021-02-06 17:40 UTC, bakerboy448 commented on docs/Sonarr/V3/Sonarr-Quality-Settings-File-Size.md
> +| Blueray-720p       | 35      | 90      |
"Bluray"

2021-02-06 17:41 UTC, bakerboy448 commented
other than the typo the numbers look good; I'll defer to @TRaSH-  on adding the table.  Seems like a good idea to me.

2021-02-06 17:43 UTC, rcdailey commented on docs/Sonarr/V3/Sonarr-Quality-Settings-File-Size.md
> +| Blueray-720p       | 35      | 90      |
Dammit! Thank you :)

2021-02-06 18:05 UTC, bakerboy448 approved these changes

2021-02-07 15:50 UTC, TRaSH- commented
Merged with #139 being i couldn't merge my changes with yours.

2021-02-07 15:50 UTC, closed without merging

2021-02-07 15:56 UTC, rcdailey commented
For future reference, I highly recommend merging PRs as-is or requesting more changes if you'd like. Commit metadata like commit author isn't lost in that case, and things come in more incrementally. For example, in your case I would have done this instead:

1. Left feedback on this PR requesting the screenshot removed, which I would have gladly done
2. Merge my PR as-is
3. You make a follow up PR with the anime quality settings